##
## EPITECH PROJECT, 2022
## OOP_arcade_2018
## File description:
## Makefile created by tomcousin,
##

SHELL	=	bash

all:	nibbler

nibbler:
		@make -C GameModuleNibbler

clean:
		@make -C GameModuleNibbler clean

fclean:	clean
		@make -C GameModuleNibbler fclean

re:		fclean all

.PHONY:	clean fclean all re nibbler